FROM wordpress:6.7.1-php8.3-apache
RUN rm -rf /var/www/html/wp-content
COPY wordpress-data/ /var/www/html/
RUN chown -R www-data:www-data /var/www/html \
  && find /var/www/html -type d -exec chmod 755 {} \; \
  && find /var/www/html -type f -exec chmod 644 {} \;
RUN apt-get update && apt-get install -y \
  libzip-dev \
  unzip \
  && docker-php-ext-install zip

EXPOSE 80

